### ISSUE TITLE
Mouse clicking wrong place in dual monitor

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#48]
_Original author: jt...@tokbox.com (April 15, 2013 20:54:27)_

<b>What steps will reproduce the problem?</b>
1. Search for an image that exists on the secondary monitor (in my case, the one on the right side)
2. Call mouse.click(region.getCenter())

<b>What is the expected output? What do you see instead?</b>
I expect the mouse to click that image in the center
The mouse does jump to the image on the second monitor (the one on the right), then you can see it move to the same coordinates on the first monitor (the one on the left) as if it thinks the button is on the first monitor

<b>What version of the product are you using? On what operating system?</b>
Windows 7 Ultimate, 64 bit

<b>Please provide any additional information below.</b>
- Primary monitor is on the left. Secondary monitor is on the right.
- This seems to not be an issue for Mac OSX
- It will click the right button if I add an offset to region.getRelativeScreenLocation
- Sikuli seems to think that my primary monitor is my secondary monitor, and vise versa...I had to call desktop_screen.setScreen(new DesktopScreen(1)) for it to detect the image on my primary monitor. My taskbar is on my left monitor. Also when I goto my monitor setup, windows recognize my left monitor as my main display.

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=48_

**Comment by river-of-code** [comment]
How was this issue solved? I am having the same issue.
